[colors.bright]
black = "#9DA9A0"
red = "#E67E80"
green = "#A7C080"
yellow = "#DBBC7F"
blue = "#7FBBB3"
magenta = "#D699B6"
cyan = "#83C092"
white = "#F1E4C5"

[colors.normal]
black = "#9DA9A0"
red = "#E67E80"
green = "#A7C080"
yellow = "#DBBC7F"
blue = "#7FBBB3"
magenta = "#D699B6"
cyan = "#83C092"
white = "#F1E4C5"

[colors.primary]
background = "#2D353B"
foreground = "#D3C6AA"